=== Milliamper/DTKUG0_XMLGyak/XMLTaskDTKUG0/DomParseDTKUG0/XMLSchemadtkug0.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:element name="auto_nt_service">
        <xs:complexType>
            <xs:sequence>
                <xs:choice maxOccurs="unbounded">
                    <xs:element name="cegjegyzek" type="cegjegyzek_type"/>
                    <xs:element name="ceg" type="ceg_type"/>
                    <xs:element name="muhely" type="muhely_type"/>
                    <xs:element name="raktar" type="raktar_type"/>
                    <xs:element name="auto" type="auto_type"/>
                    <xs:element name="tulajdonos" type="tulajdonos_type"/>
                    <xs:element name="futar" type="futar_type"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>

        <xs:key name="cegjegyzekid_primaryKey">
            <xs:selector xpath="cegjegyzek"/>
            <xs:field xpath="@cegjegyzekid"/>
        </xs:key>
        <xs:keyref name="cegid_foreignKey" refer="cegid_primaryKey">
            <xs:selector xpath="cegjegyzek"/>
            <xs:field xpath="@cegid"/>
        </xs:keyref>
        <xs:key name="cegid_primaryKey">
            <xs:selector xpath="ceg"/>
            <xs:field xpath="@cegid"/>
        </xs:key>
        <xs:key name="mid_primaryKey">
            <xs:selector xpath="muhely"/>
            <xs:field xpath="@mid"></xs:field>
        </xs:key>
        <xs:keyref name="cegid2_foreignKey" refer="cegid_primaryKey">
            <xs:selector xpath="muhely"/>
            <xs:field xpath="@cegid"/>
        </xs:keyref>
        <xs:key name="cikkszam_primaryKey">
            <xs:selector xpath="raktar"/>
            <xs:field xpath="@cikkszam"/>
        </xs:key>
        <xs:key name="alvazszam_primaryKey">
            <xs:selector xpath="auto"/>
            <xs:field xpath="@alvazszam"/>
        </xs:key>
        <xs:keyref name="ugyfelid_foreignKey" refer="ugyfelid_primaryKey">
            <xs:selector xpath="auto"/>
            <xs:field xpath="@ugyfelid"/>
        </xs:keyref>
        <xs:key name="ugyfelid_primaryKey">
            <xs:selector xpath="tulajdonos"/>
            <xs:field xpath="@ugyfelid"/>
        </xs:key>
        <xs:keyref name="mid_foreignKey" refer="mid_primaryKey">
            <xs:selector xpath="futar"/>
            <xs:field xpath="@mid"/>
        </xs:keyref>
        <xs:keyref name="cikkszam_foreignKey" refer="cikkszam_primaryKey">
            <xs:selector xpath="futar"/>
            <xs:field xpath="@cikkszam"/>
        </xs:keyref>
    </xs:element>
    
    <xs:complexType name="cegjegyzek_type">
        <xs:sequence>
            <xs:element name="bejegyzett_cegek" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="cegid" type="xs:string" use="required"/>
        <xs:attribute name="cegjegyzekid" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="ceg_type">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="szekhely" type="szekhely_type"/>
        </xs:sequence>
        <xs:attribute name="cegid" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="muhely_type">
        <xs:sequence>
            <xs:element name="javitando_auto" type="javitando_auto_type"/>
        </xs:sequence>
        <xs:attribute name="cegid" type="xs:string" use="required"/>
        <xs:attribute name="mid" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="raktar_type">
        <xs:sequence>
            <xs:element name="alkatreszek" type="alkatreszek_type"/>
        </xs:sequence>
        <xs:attribute name="cikkszam" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="auto_type">
        <xs:sequence>
            <xs:element name="marka" type="xs:string"/>
            <xs:element name="tipus" type="xs:string"/>
            <xs:element name="km_ora_allasa" type="km_ora_allasa_type"/>
        </xs:sequence>
        <xs:attribute name="ugyfelid" type="xs:string" use="required"/>
        <xs:attribute name="alvazszam" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="tulajdonos_type">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="cim" type="xs:string"/>
            <xs:element name="szulido" type="szulido_type"/>
        </xs:sequence>
        <xs:attribute name="ugyfelid" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="futar_type">
        <xs:sequence>
            <xs:element name="varhato_erk" type="varhato_erk_type"/>
        </xs:sequence>
        <xs:attribute name="mid" type="xs:string" use="required"/>
        <xs:attribute name="cikkszam" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="szekhely_type">
        <xs:sequence>
            <xs:element name="cim" type="xs:string"/>
            <xs:element name="telefonszam" type="telefonszam_type"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="javitando_auto_type">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z]+\s[a-zA-Z]+"/> <!-- "string string" -->
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="alkatreszek_type">
        <xs:restriction base="xs:string">
          <xs:minLength value="3" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="km_ora_allasa_type">
        <xs:restriction base="xs:integer">
          <xs:minInclusive value="1"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="szulido_type">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{4}\.(0[1-9]|1[012])\.(0[1-9]|[12][0-9]|3[01])"/> <!-- YYYY.MM.DD -->
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="varhato_erk_type">
        <xs:restriction base="xs:string">
            <xs:pattern value="([0-9]|0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]"/> <!-- HH.MM -->
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="telefonszam_type">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{2}-\d{3}-\d{2}-\d{2}"/>
            <xs:pattern value="\d{2}-\d{3}-\d{3}"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== Milliamper/DTKUG0_XMLGyak/XMLTaskDTKUG0/DomParseDTKUG0/XMLdtkug0.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?><auto_nt_service xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemadtkug0.xsd">
    
    <cegjegyzek cegid="1" cegjegyzekid="1">
        <bejegyzett_cegek>Stop'n go</bejegyzett_cegek>
    </cegjegyzek>
    <cegjegyzek cegid="2" cegjegyzekid="2">
        <bejegyzett_cegek>Nonstop service</bejegyzett_cegek>
    </cegjegyzek>
    <cegjegyzek cegid="3" cegjegyzekid="3">
        <bejegyzett_cegek>Bosch Car Service</bejegyzett_cegek>
    </cegjegyzek>

    <ceg cegid="1">
        <nev>Stop'n go</nev>
        <szekhely>
            <cim>Miskolc, Soltész Nagy Kálmán utca 36.</cim>
            <telefonszam>46-343-565</telefonszam>
        </szekhely>
    </ceg>
    <ceg cegid="2">
        <nev>Nonstop service</nev>
        <szekhely>
            <cim>Miskolc, Fonoda utca 36.</cim>
            <telefonszam>46-123-414</telefonszam>
        </szekhely>
    </ceg>
    <ceg cegid="3">
        <nev>Bosch Car Service</nev>
        <szekhely>
            <cim>Karcag, Tőkés utca 25.</cim>
            <telefonszam>53-555-100</telefonszam>
        </szekhely>
    </ceg>

    <muhely cegid="1" mid="1">
        <javitando_auto>Fiat Multipla</javitando_auto>
    </muhely>
    <muhely cegid="2" mid="2">
        <javitando_auto>Kia Ceed</javitando_auto>
    </muhely>
    <muhely cegid="3" mid="3">
        <javitando_auto>Honda Civic</javitando_auto>
    </muhely>

    <raktar cikkszam="1">
        <alkatreszek>Kerekcsapagy</alkatreszek>
    </raktar>
    <raktar cikkszam="2">
        <alkatreszek>ECU</alkatreszek>
    </raktar>
    <raktar cikkszam="3">
        <alkatreszek>Motorolaj</alkatreszek>
    </raktar>

    <auto alvazszam="JH4KA4660LC006262" ugyfelid="1">
        <marka>Opel</marka>
        <tipus>Corsa</tipus>
        <km_ora_allasa>250000</km_ora_allasa>
    </auto>
    <auto alvazszam="J8DE5B16477903094" ugyfelid="2">
        <marka>Kia</marka>
        <tipus>Ceed</tipus>
        <km_ora_allasa>98000</km_ora_allasa>
    </auto>
    <auto alvazszam="JH4KA2550HC005889" ugyfelid="3">
        <marka>Honda</marka>
        <tipus>Civic</tipus>
        <km_ora_allasa>250000</km_ora_allasa>
    </auto>

    <tulajdonos ugyfelid="1">
        <nev>Kiss Ramóna</nev>
        <cim>5300 Karcag, Déryné utca 10</cim>
        <szulido>1999.01.01</szulido>
    </tulajdonos>
    <tulajdonos ugyfelid="2">
        <nev>Tóth Fanni</nev>
        <cim>Kiskunfélegyháza, Napsugár út. 50</cim>
        <szulido>1987.10.10</szulido>
    </tulajdonos>
    <tulajdonos ugyfelid="3">
        <nev>Kiss Tamás</nev>
        <cim>3434 Malyi, Rakoczi ut 14.</cim>
        <szulido>1999.01.01</szulido>
    </tulajdonos>

    <futar cikkszam="1" mid="1">
        <varhato_erk>15:15</varhato_erk>
    </futar>
    <futar cikkszam="2" mid="2">
        <varhato_erk>10:00</varhato_erk>
    </futar>
    <futar cikkszam="3" mid="3">
        <varhato_erk>6:00</varhato_erk>
    </futar>

</auto_nt_service>

=== Milliamper/DTKUG0_XMLGyak/XMLTaskDTKUG0/XMLdtkug0.xml
<?xml version="1.0" encoding="utf-8"?>

<auto_nt_service xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemadtkug0.xsd">
    
    <cegjegyzek cegid="a" cegjegyzekid="aa">
        <bejegyzett_cegek>Stop'n go</bejegyzett_cegek>
    </cegjegyzek>
    <cegjegyzek cegid="b" cegjegyzekid="bb">
        <bejegyzett_cegek>Stop'n go</bejegyzett_cegek>
    </cegjegyzek>
    <cegjegyzek cegid="c" cegjegyzekid="cc">
        <bejegyzett_cegek>Stop'n go</bejegyzett_cegek>
    </cegjegyzek>

    <ceg cegid="a">
        <nev>Stop'n go</nev>
        <szekhely>
            <cim>Miskolc, Soltész Nagy Kálmán utca 36.</cim>
            <telefonszam>46-343-565</telefonszam>
        </szekhely>
    </ceg>
    <ceg cegid="b">
        <nev>Nonstop service</nev>
        <szekhely>
            <cim>Miskolc, Fonoda utca 36.</cim>
            <telefonszam>46-123-414</telefonszam>
        </szekhely>
    </ceg>
    <ceg cegid="c">
        <nev>Bosch Car Service</nev>
        <szekhely>
            <cim>Karcag, Tőkés utca 25.</cim>
            <telefonszam>53-555-100</telefonszam>
        </szekhely>
    </ceg>

    <muhely cegid="a" mid="m1">
        <javitando_auto>Honda Jazz</javitando_auto>
    </muhely>
    <muhely cegid="b" mid="m2">
        <javitando_auto>Mazda 3</javitando_auto>
    </muhely>
    <muhely cegid="c" mid="m3">
        <javitando_auto>Hyundai i20</javitando_auto>
    </muhely>

    <raktar cikkszam="qwert12">
        <alkatreszek>Injektor</alkatreszek>
    </raktar>
    <raktar cikkszam="xfgje55">
        <alkatreszek>ECU</alkatreszek>
    </raktar>
    <raktar cikkszam="lobdy87">
        <alkatreszek>MAP sensor</alkatreszek>
    </raktar>

    <auto ugyfelid="a1" alvazszam="JH4KA4660LC006262">
        <marka>Honda</marka>
        <tipus>Jazz</tipus>
        <km_ora_allasa>20000</km_ora_allasa>
    </auto>
    <auto ugyfelid="a2" alvazszam="J8DE5B16477903094">
        <marka>Mazda</marka>
        <tipus>3</tipus>
        <km_ora_allasa>98000</km_ora_allasa>
    </auto>
    <auto ugyfelid="a3" alvazszam="JH4KA2550HC005889">
        <marka>Hyundai</marka>
        <tipus>i20</tipus>
        <km_ora_allasa>110000</km_ora_allasa>
    </auto>

    <tulajdonos ugyfelid="a1">
        <nev>Szalai Márton</nev>
        <cim>Miskolc, Felsőruzsin krt. 34</cim>
        <szulido>1999.03.18</szulido>
    </tulajdonos>
    <tulajdonos ugyfelid="a2">
        <nev>Tóth Fanni</nev>
        <cim>Kiskunfélegyháza, Napsugár út. 50</cim>
        <szulido>1987.10.10</szulido>
    </tulajdonos>
    <tulajdonos ugyfelid="a3">
        <nev>Nagy Béla</nev>
        <cim>Berettyóújfalu, Kossuth utca. 10</cim>
        <szulido>1974.01.29</szulido>
    </tulajdonos>

    <futar mid="m1" cikkszam="qwert12">
        <varhato_erk>15:00</varhato_erk>
    </futar>
    <futar mid="m2" cikkszam="xfgje55">
        <varhato_erk>10:00</varhato_erk>
    </futar>
    <futar mid="m3" cikkszam="lobdy87">
        <varhato_erk>6:00</varhato_erk>
    </futar>

</auto_nt_service>
