=== Milliamper/DTKUG0_XMLGyak/DTKUG0_1005/SzM_konyv.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="konyvek">


	<xs:complexType>
	
	
		<xs:sequence>
	
			<xs:element name="konyv" maxOccurs="unbounded">
		
				<xs:complexType> <!--könyv elemnek több eleme van, komplex jelölőelem-->
			
					<xs:sequence> <!--gyerek elemeknek rögzített sorrendjét jelöli-->
						<xs:element name="cim" type ="xs:string"/>
						<xs:element name="kiadasi_eve" type="xs:unsignedShort"/>
						<xs:element name="kiado" type="xs:string"/>
						<xs:element name="szerzo" type="xs:string" maxOccurs="unbounded"/>
					</xs:sequence>
				
				<xs:attribute name="id" type="xs:string" use="required"/>
				
				</xs:complexType>
			
			</xs:element>

		</xs:sequence>
	
	</xs:complexType>

</xs:element>

</xs:schema>

=== Milliamper/DTKUG0_XMLGyak/DTKUG0_1005/SzM_konyv.xml
<?xml version="1.0" encoding="utf-8"?>
<!--DOCTYPE konyvek SYSTEM "SzM_konyv.dtd"-->

<!--<xsi:schemaLocation="http://www.w3schools.com SzM_konyv.xsd"/>-->


<konyvek xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SzM_konyv.xsd">

	<konyv id="a">
		<cim>Szolgáltatásalapú világ</cim>
        <kiadasi_eve>2013</kiadasi_eve>
		<kiado>Libri</kiado>
		<szerzo>Gottdank Tibor</szerzo>
	</konyv>

    <konyv id="b">
		<cim>Intelligens érzékelők az orvosbiológiában</cim>
        <kiadasi_eve>2013</kiadasi_eve>
		<kiado>Libri</kiado>
		<szerzo>Kovács Ferenc</szerzo>
	</konyv>

    <konyv id="c">
		<cim>Számítógépes eszközök hálózatba kötése - Lépésről lépésre</cim>
        <kiadasi_eve>2011</kiadasi_eve>
		<kiado>Libri</kiado>
		<szerzo>Ciprian Adrian Rusen</szerzo>
	</konyv>

</konyvek>
