=== Milliamper/DTKUG0_XMLGyak/DTKUG0_0928/SzM_konyv.dtd
<!DOCTYPE konyvek [
<!ELEMENT konyvek (konyv+)>
<!ELEMENT konyv (cim,kiadasi_eve,kiado,szerzo)>
<!ELEMENT cim (#PCDATA)>
<!ELEMENT kiadasi_eve (#PCDATA)>
<!ELEMENT kiado (#PCDATA)>
<!ELEMENT szerzo (#PCDATA)>
]>

=== Milliamper/DTKUG0_XMLGyak/DTKUG0_0928/SzM_konyv.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE konyvek SYSTEM "SzM_konyv.dtd">

<konyvek>

	<konyv id="a">
		<cim>Bevezetés a C#-ba</cim>
        <kiadasi_eve>2008</kiadasi_eve>
		<kiado>Libri</kiado>
		<szerzo>Csató Endre</szerzo>
	</konyv>

    <konyv id="b">
		<cim>Java alapok</cim>
        <kiadasi_eve>2015</kiadasi_eve>
		<kiado>Mozaik</kiado>
		<szerzo>Tamás Ádám</szerzo>
	</konyv>

    <konyv id="c">
		<cim>Adatbáziskezelés</cim>
        <kiadasi_eve>2000</kiadasi_eve>
		<kiado>Álomgyár</kiado>
		<szerzo>John Wick</szerzo>
	</konyv>

</konyvek>
